/**
* \file  Radeau.h
* \brief fichier qui regroupe les fonctionnalité et les attributs de la classe Bateau
* \author Havez Maxime
* \author Thiveux Gareth
* \version 1.0
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include <cstdlib>
#include <string>
#include <iostream>

using namespace std;

class Bateau
{

	protected :

		bool peutPorterTresor;
		bool peutJouer2Des;
		bool peutTirer;
		bool peutEtreVise;
		pair<int,int> position;

	public :

		/*vituelle pure*/

		/**
		* \fn virtual string typeBateau() = 0
		* \brief fonction virtuelle pure qui doit permettre aux héritié de donner leur nom de classe 
		*
		* \return le string du nom de la classe
		*/
		virtual string typeBateau() = 0;

		/**
		* \fn virtual void init() =0
		* \brief fonction virtuelle pure qui doit permettre aux héritié d'initialiser l'instance
		*/
		virtual void init() =0;

		
		virtual pair<int,int> getPosition();
		virtual bool peutTirer();
		virtual bool peutEtreVise();
		virtual bool peutJouer2Des();
		virtual void positionner(pair<int,int> p);
}; 

inline pair<int,int> Bateau::getPosition(){
	return position;
}
inline bool Bateau::peutTirer(){
	return peutTirer;
}
inline bool Bateau::peutEtreVise(){
	return peutEtreVise;
}
inline bool Bateau::peutJouer2Des(){
	return peutJouer2Des;
}