//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include <cstdlib>
#include <string>

using namespace std;

class Bateau
{

	protected :

		bool peutPorterTresor;
		bool peutJouer2Des;
		bool peutTirer;
		bool peutEtreVise;
		pair<int,int> position;

	public :

		/*vituelle pure*/
		virtual string typeBateau() = 0;
		virtual void init() =0;

		virtual pair<int,int> getPosition();
		virtual bool peutTirer();
		virtual bool peutEtreVise();
		virtual bool peutJouer2Des();
}; 

inline pair<int,int> Bateau::getPosition(){
	return position;
}
inline bool Bateau::peutTirer(){
	return peutTirer;
}
inline bool Bateau::peutEtreVise(){
	return peutEtreVise;
}
inline bool Bateau::peutJouer2Des(){
	return peutJouer2Des;
}