/**
* \file  Radeau.h
* \brief fichier qui regroupe les fonctionnalité et les attributs de la classe Caravelle
* \author Havez Maxime
* \author Thiveux Gareth
* \version 1.0
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Bateau.h"
using namespace std;

class Caravelle : public Bateau
{

	public :

		string typeBateau();
		void init();
		
		Caravelle();

}; 

