/**
* \file  Caravelle.h
* \brief fichier qui regroupe les fonctionnalités et les attributs de la classe Caravelle
* \author Havez Maxime
* \author Thiveux Gareth
* \version 1.0
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Bateau.h"
using namespace std;

class Caravelle : public Bateau
{

	public :

		/**
		* \fn virtual string typeBateau() = 0
		* \brief fonction hérité qui permet de donner le nom de la classe 
		* \return string le nom de la classe
		*/
		string typeBateau();
		/**
		* \fn void init()
		* \brief fonction hérité qui permet d'initialiser l'instance
		*/
		void init();
		/**
		* \fn Caravelle()
		* \brief constructeur par défaut qui initialise le bateau
		*/
		Caravelle();

}; 

