//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class CaseIle : public Case Fixe, public Case
{
	private :


	protected :


	public :


	private :


	protected :


	public :


}; 

