//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class CaseBordurePlateau : public Case Fixe, public CaseNavigable
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		virtual CaseBordurePalteau CaseOpposee();
		virtual bool DuelPossible();
		virtual void getEtat();

}; 

