//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class CaseTresor : public CaseContourIle
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		virtual void getEtat();

}; 

