/**
*\file  enum.h
*\brief File which contains the enumaration conresponding to the Etats
*\author Maxime HAVEZ
*\author Gareth THIVEUX
*\version 1.0
*/

enum enumEtat {
	ATTENTENBJOUEURS,
	ATTENTEINITIALISATION,
	ATTENTEPREMLANCERDE,
	ATTENTELANCERDE,
	ATTENTECHOIXBATEAU,
	PROPOSEDEPLACEMENT,
	ATTENTEDEPLACEMENT,
	DUEL,
	ATTENTECANONPUISSANCE,
	ATTENTECANONANGLE,
	ETATCANONFIN,
	ETATTRESOR,
	ETATDEPOS
};