//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <cstdlib>
#include <iostream>
#include "Bateau.h"

using namespace std;

class Joueur
{

	public :

		string nom;
		int numero;
		bool gagnant;

	public :

		virtual string nom();
		virtual int numero();
		virtual void modifierNumero(int i);
		Joueur(string n, int coul, int num);
		virtual Bateau getBateau(int i);

}; 

