//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>{ context MoteurJeu::execute() return : courant.execute() }</remarks>
class MoteurJeu
{
	private :

		int nbJoueurs;
		Etat courant;
		int j_indJoueurCourant;
		Joueur[] tabJoueurs;
		bool finPartie;

	protected :


	public :


	private :


	protected :


	public :

		virtual void setEtat(Etat e);
		virtual void execute();

}; 

