//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class AffichageWPF
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		virtual void clicDe();
		virtual void clicCase();
		virtual void clicLancerPartie();
		virtual void creerFenetreInit();
		virtual void rafraichir();
		virtual void creerFenetreTir();

}; 

