//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>execute() => amène le Joueur sur une case. Selon la case on lance  un état Tir, Depot, </remarks>
class AttenteDeplacement : public Etat
{
	private :

		MoteurJeu motor;

	public :

		virtual void execute();

}; 

