//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>
/// le tableau resDe contient les résultats du lancement des deux dé par joueur(non ordonné)
/// j_indJoueur = 0 
/// </remarks>
class AttentePremLancerDe : public Etat
{
	private :

		static int[] resDe;
		Moteur motor;
		static int nbLance;

	protected :


	public :


	private :


	protected :


	public :

		virtual void execute();
		virtual void determinerOrdre();

}; 

