/**
* \file  Bateau.h
* \brief fichier qui regroupe les fonctionnalité et les attributs de la classe Bateau
* \author Havez Maxime
* \author Thiveux Gareth
* \version 1.0
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include <cstdlib>
#include <string>
#include <iostream>

using namespace std;

class Bateau
{

	protected :

		bool peutPorterTresor;
		bool peutJouer2Des;
		bool peutTirer;
		bool peutEtreVise;
		pair<int,int> position;

	public :

		/*vituelle pure*/

		/**
		* \fn virtual string typeBateau() = 0
		* \brief fonction virtuelle pure qui doit permettre aux héritié de donner leur nom de classe 
		*
		* \return le string du nom de la classe
		*/
		virtual string typeBateau() = 0;
		/**
		* \fn virtual void init() =0
		* \brief fonction virtuelle pure qui doit permettre aux héritié d'initialiser l'instance
		*/
		virtual void init() =0;



		/**
		* \fn pair<int,int> getPosition()
		* \brief fonction virtuelle qui retourne la position du bateau
		*
		* \return pair<int,int> la position du bateau
		*/
		virtual pair<int,int> getPosition();
		/**
		* \fn bool peutTirer()
		* \brief fonction virtuelle qui retourne la capacité d'un bateau à tirer
		*
		* \return bool true si le bateau peut tirer
		*/
		virtual bool peutTirer();
		/**
		* \fn bool peutEtreVise()
		* \brief fonction virtuelle qui retourne la capacité d'un bateau à pouvoir être tiré
		*
		* permet de distinguer le radeau qui ne peut pas être tiré
		*
		* \return bool true si le bateau peut être tirer
		*/
		virtual bool peutEtreVise();
		/**
		* \fn bool peutJouer2Des()
		* \brief fonction virtuelle qui retourne la capacité d'un bateau à pouvoir lancer 2 Dé
		*
		* permet de distinguer la caravelle qui peut lancer 2 dés
		*
		* \return bool true si le bateau peut être lancer 2 dés
		*/
		virtual bool peutJouer2Des();
		/**
		* \fn void positionner(pair<int,int> p)
		* \brief fonction virtuelle qui permet de positionner un bateau à une position précise
		* \param[in] pair<int,int> une position
		*/
		virtual void positionner(pair<int,int> p);
}; 

inline pair<int,int> Bateau::getPosition(){
	return position;
}
inline bool Bateau::peutTirer(){
	return peutTirer;
}
inline bool Bateau::peutEtreVise(){
	return peutEtreVise;
}
inline bool Bateau::peutJouer2Des(){
	return peutJouer2Des;
}