//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class Dé
{
	private :

		object valeurDe1;
		object valeurDe2;

	protected :


	public :


	private :


	protected :


	public :

		virtual void lancerDe();

}; 

