//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


#include "EtatTir.h"

class EtatCanonFin : public EtatTir
{

	public :

		void execute();

}; 

