//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class FenetreInit
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		virtual void clicNbJoueurs2();
		virtual void clicNbJoueurs4();
		virtual void clicInit();
		virtual void fermerFenetre();
		virtual void champNom();
		virtual void champCouleur();
		virtual void raffraichir();
		virtual void clicNbJoueurs3();

}; 

