//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class FenetreTir
{
	private :


	protected :


	public :


	private :


	protected :


	public :

		virtual void champPuissance();
		virtual void champAngle();
		virtual void fermerFenetre();
		virtual void clicTir();
		virtual void raffraichir();
		virtual void clicRefuserDuel();

}; 

