//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Bateau.h"
using namespace std;

class Fregate : public Bateau
{

	public :

		string typeBateau();
		void init();

		Fregate();
}; 

