//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class Plateau
{
	private :

		int longueur;
		int largeur;

	protected :


	public :


	private :


	protected :


	public :

		virtual int largeur();
		virtual int longueur();

}; 

