//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>Si le nbJoueur=2 Execute de l'état précédent propose cet état</remarks>
class AttenteChoixBateau : public Etat
{
	private :

		Moteur motor;

	protected :


	public :


	private :


	protected :


	public :

		virtual void execute();

}; 

