//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>
/// execute() => qui appel la fonction Motor.de.lanceDe()
/// 
/// vérifier finPartie=false
/// </remarks>
class AttenteLancerDe : public Etat
{
	private :

		Moteur motor;

	protected :


	public :


	private :


	protected :


	public :

		virtual void choisirDe();
		virtual void execute();

}; 

