//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>execute() => rentrer nbjoueur couleur et nom (puis Joueur(j,nom,coul))</remarks>
class AttenteInitialisation : public Etat
{
	private :

		Moteur motor;

	protected :


	public :


	private :


	protected :


	public :

		virtual void execute();

}; 

