//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class Bateau
{
	private :


	protected :

		bool peutPorterTresor;
		bool peutJouer2Des;
		bool peutTirer;
		bool peutEtreVise;
		pair<int,int> position;

	public :


	private :


	protected :


	public :

		abstract string typeBateau();
		virtual pair<int,int> getPosition();
		abstract void init();

}; 

