//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class CaseNavigable : public Case
{
	private :

		bool bateau;

	protected :


	public :


	private :


	protected :


	public :

		virtual bool hasBateau();
		virtual void getState();

}; 

