//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public interface Etat 
{
	MoteurJeu MoteurJeu; { get;set; }

	void execute();

}

