//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>execute() =>  Ouvre une fenêtre, lance la selection de la puissance et de l'angle du tir, puis créer le tir grace a la fonction du canon</remarks>
class EtatTir : public Etat
{
	private :


	protected :

		Moteur motor;
		object puissance : int;
		object angle;
		bool Duel;

	public :


	private :


	protected :


	public :

		virtual void tirCanon();
		virtual void init(int p, int a);
		virtual void execute();

}; 

