//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>
/// execute() => affiche les possibilités de déplacement
/// 
/// </remarks>
class ProposeDeplacement : public Etat
{
	private :

		Moteur motor;

	protected :


	public :

		pair<int,int>[] tabCase;

	private :


	protected :


	public :

		virtual void execute();

}; 

