//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>réalisé par le wrapper</remarks>
class Adaptateur
{
	private :


	protected :


	public :


	private :


	protected :


	public :


}; 

