//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class Case
{
	private :


	protected :

		pair<int,int>  position;
		bool accessible;
		int hauteur;
		static int nbTotTresor;

	public :


	private :


	protected :


	public :

		virtual int getHauteur();
		virtual bool accessible();
		virtual pair<int,int> getPosition();
		virtual void getEtat();

}; 

