//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class Duel : public Etat
{
	private :

		Moteur motor;
		bool touche;

	protected :


	public :


	private :


	protected :


	public :

		virtual void execute();

}; 

